import { renderToStaticMarkup } from "react-dom/server"
import { describe, expect, it } from "vitest"

import { demoInvestigation } from "@/lib/demo-investigation"

import { InvestigationWorkbench } from "./investigation-workbench"

const workbenchProps = {
  assessmentRuns: [],
  assessmentRunsError: null,
  assetSnapshots: [],
  assetSnapshotsError: null,
  exposures: [],
  exposuresError: null,
  policyDecisions: [],
  policyDecisionsError: null,
  revisionHistory: [],
  dispositions: [],
  dispositionWritesEnabled: false,
  recordDispositionAction: async () => ({ status: "idle" as const, message: "" }),
}

describe("InvestigationWorkbench", () => {
  it("names every evidence relationship and preserves an authoritative conflict", () => {
    const investigation = {
      ...demoInvestigation,
      exposure: {
        ...demoInvestigation.exposure,
        authoritativeConflict: true,
        advisoryGuidance: [
          {
            source: "Synthetic maintainer advisory",
            authority: "Maintainer · Tier 1",
            affectedRange: ">=2.1.0, <2.4.3",
            fixedVersion: "2.4.3",
            relationship: "contradicts" as const,
          },
          {
            source: "Synthetic public vulnerability record",
            authority: "Public database · Tier 1",
            affectedRange: ">=2.1.0, <2.4.2",
            fixedVersion: "2.4.2",
            relationship: "contradicts" as const,
          },
        ],
      },
      recommendation: {
        ...demoInvestigation.recommendation,
        label: "More Evidence Required",
      },
      evidence: demoInvestigation.evidence.map((record, index) => ({
        ...record,
        relationships: [
          {
            claimId: demoInvestigation.claims[0].id,
            relationship: (["supports", "contradicts", "contextual"] as const)[index % 3],
          },
        ],
      })),
    }

    const html = renderToStaticMarkup(
      <InvestigationWorkbench investigation={investigation} {...workbenchProps} />,
    )

    expect(html).toContain("Material conflict")
    expect(html).toContain("No Source was selected as the winner")
    expect(html).toContain("More Evidence Required")
    expect(html).toContain("needs more evidence")
    expect(html).not.toContain("requires action")
    expect(html).toContain("Supporting")
    expect(html).toContain("Contradicting")
    expect(html).toContain("Contextual")
    expect(html).toContain("Synthetic maintainer advisory")
    expect(html).toContain("2.4.3")
    expect(html).toContain("Synthetic public vulnerability record")
    expect(html).toContain("2.4.2")
    expect(html).toMatch(/<button[^>]*disabled=""[^>]*>Record disposition/)
  })

  it("does not prescribe action when no remediation is indicated", () => {
    const investigation = {
      ...demoInvestigation,
      recommendation: {
        ...demoInvestigation.recommendation,
        label: "No Remediation Indicated",
      },
    }

    const html = renderToStaticMarkup(
      <InvestigationWorkbench investigation={investigation} {...workbenchProps} />,
    )

    expect(html).toContain("has no indicated remediation")
    expect(html).not.toContain("requires action")
  })

  it("presents hybrid component ranks and the complete Embedding Space identity", () => {
    const html = renderToStaticMarkup(
      <InvestigationWorkbench investigation={demoInvestigation} {...workbenchProps} />,
    )

    expect(html).toContain(demoInvestigation.retrieval.query)
    expect(html).toContain("Hybrid · RRF")
    expect(html).toContain("Full-text rank")
    expect(html).toContain("Vector rank")
    expect(html).toContain("Fused rank")
    expect(html).toContain("PostgreSQL full-text + pgvector")
    expect(html).toContain("Rank 1 is the strongest fused result")
    expect(html).toContain(demoInvestigation.retrieval.configurationVersion)
    expect(html).toContain("Embedding Space")
    expect(html).toContain(demoInvestigation.retrieval.embeddingSpace.identity)
    expect(html).toContain(demoInvestigation.retrieval.embeddingSpace.modelArtifact)
    expect(html).toContain(demoInvestigation.retrieval.embeddingSpace.artifactDigest)
    expect(html).toContain(demoInvestigation.retrieval.embeddingSpace.retrievalInstruction)
    expect(html).toContain(demoInvestigation.retrieval.embeddingSpace.normalizer)
    expect(html).toContain(demoInvestigation.retrieval.embeddingSpace.passageConstructionVersion)
    expect(html.indexOf("sha256:21df…0c91")).toBeLessThan(
      html.indexOf("sha256:65bc…8a20"),
    )
  })

  it("distinguishes a live local Revision from the precomputed demonstration", () => {
    const live = {
      ...demoInvestigation,
      meta: { ...demoInvestigation.meta, mode: "live" as const },
    }

    const html = renderToStaticMarkup(
      <InvestigationWorkbench investigation={live} {...workbenchProps} />,
    )

    expect(html).toContain("Live local revision")
    expect(html).toContain("This Revision was generated by the local Investigation runner.")
    expect(html).not.toContain("Synthetic precomputed demo")
  })

  it("distinguishes the model proposal from deterministic authorization and stopping", () => {
    const incomplete = {
      ...demoInvestigation,
      meta: { ...demoInvestigation.meta, status: "incomplete" as const },
      stoppingReason: "The proposed Evidence Gap follow-up failed deterministic validation.",
      evidenceGap: {
        identity: "gap-fixed-version",
        kind: "insufficient",
        description: "The fixed version is not supported by the retrieved passages.",
      },
      followUp: {
        tool: "search_captured_exposure_evidence",
        target: "exposure:EXP-1042",
        sourceIdentity: "osv",
        evidenceType: "affected",
        proposedAssistanceClass: "C1",
        proposedActionLevel: "A1",
        authorized: false,
        executed: false,
        reason: "follow_up_target_outside_exposure",
        issues: ["follow_up_target_outside_exposure"],
        policyAssistanceClass: "C1",
        policyActionLevel: "A1",
        policyResult: "allowed",
      },
    }

    const html = renderToStaticMarkup(
      <InvestigationWorkbench investigation={incomplete} {...workbenchProps} />,
    )

    expect(html).toContain("Model proposal")
    expect(html).toContain("Deterministic authorization")
    expect(html).toContain("Not authorized")
    expect(html).toContain(incomplete.stoppingReason)
    expect(html).not.toContain("chain-of-thought")
  })

  it("presents immutable Revision history separately from human Dispositions", () => {
    const html = renderToStaticMarkup(
      <InvestigationWorkbench
        investigation={{
          ...demoInvestigation,
          meta: { ...demoInvestigation.meta, mode: "live" as const, revision: "REV-0002" },
        }}
        {...workbenchProps}
        revisionHistory={[
          {
            investigationId: "investigation-1",
            id: "revision-2",
            revisionNumber: 2,
            assessmentRunId: "assessment-2",
            assetSnapshotId: "snapshot-1",
            createdAt: "2026-09-04T15:00:00Z",
            status: "complete",
            stoppingCondition: "completed",
            recommendation: "Monitor",
            changes: [
              "Recommendation: Planned Remediation → Monitor",
              "Prompt: claims-recommendation-v1 → claims-recommendation-v2",
            ],
          },
          {
            investigationId: "investigation-1",
            id: "revision-1",
            revisionNumber: 1,
            assessmentRunId: "assessment-1",
            assetSnapshotId: "snapshot-1",
            createdAt: "2026-09-04T14:00:00Z",
            status: "complete",
            stoppingCondition: "completed",
            recommendation: "Planned Remediation",
            changes: ["Initial Revision"],
          },
        ]}
        dispositions={[
          {
            id: "disposition-1",
            investigationId: "investigation-1",
            investigationRevisionId: "revision-1",
            exposureId: "exposure-1",
            assetSnapshotId: "snapshot-1",
            kind: "remediate",
            author: "AppSec reviewer",
            rationale: "The published fixed version is approved for rollout.",
            expirationDate: null,
            reviewDate: null,
            createdAt: "2026-09-04T16:00:00Z",
          },
        ]}
        dispositionWritesEnabled
      />,
    )

    expect(html).toContain("Investigation history")
    expect(html).toContain("Creation circumstances")
    expect(html).toContain("Recommendation: Planned Remediation → Monitor")
    expect(html).toContain("Prompt: claims-recommendation-v1 → claims-recommendation-v2")
    expect(html).toContain("System Recommendation")
    expect(html).toContain("Human Dispositions")
    expect(html).toContain("Remediate")
    expect(html).toContain("AppSec reviewer")
    expect(html).toContain("Risk acceptance requires a rationale")
    expect(html).toContain("Authenticated as the configured local operator")
    expect(html).toContain('name="kind"')
    expect(html).toContain('value="accept_risk"')
    expect(html).toContain('name="reviewDate"')
  })
})
