import type {
  InvestigationConfiguration,
  WorkbenchInvestigation,
} from "./workbench-investigation"

export type {
  ClaimKind,
  EvidenceRelationship,
  InvestigationClaim,
  InvestigationStage,
  WorkbenchEvidenceRecord as DemoEvidenceRecord,
  WorkbenchInvestigation as DemoInvestigation,
} from "./workbench-investigation"

const demoConfiguration: InvestigationConfiguration = {
  applicationRelease: "synthetic-demo",
  graphVersion: "demo-graph-0.1",
  promptVersion: "demo-001",
  policyVersion: "demo-policy-0.1",
  parserVersion: "demo-parser-001",
  retrievalConfigurationVersion: "postgres-hybrid-rrf-v1",
  sourcePolicyVersion: "explicit-source-allowlist-v1",
  sourceAdapterVersions: ["synthetic-advisories-v1", "synthetic-kev-v1", "synthetic-epss-v1"],
  generationModel: {
    provider: "synthetic",
    modelArtifact: "precomputed-demo",
    artifactDigest: "not-applicable-precomputed",
  },
  embeddingSpace: {
    identity: "sha256:7eb54bd7f75166528a13264eec28f37aba439cd090aec84bb9a7f1d12f4736c1",
    provider: "ollama-local",
    modelArtifact: "qwen3-embedding:0.6b",
    artifactDigest:
      "sha256:84a319513af54a65d1ad379f244411b221a26b3477055f823cfef7743bcf4f9e",
    dimensions: 1024,
    retrievalInstruction: "Represent this cybersecurity query for evidence passage retrieval: ",
    normalizer: "l2-v1",
    passageConstructionVersion: "source-aware-passage-v1",
  },
}

export const demoInvestigation: WorkbenchInvestigation = {
  meta: {
    mode: "precomputed",
    status: "incomplete",
    repository: "northstar-labs/harbor-api",
    commit: "4f92c7d",
    projectRoot: "services/api",
    environment: "Python 3.12 · macOS arm64 · default extras",
    revision: "REV-0007",
    capturedAt: "2026-08-28 16:42 UTC",
  },
  exposure: {
    id: "EXP-1042",
    vulnerability: "DEMO-2026-0042",
    aliases: ["DEMO-GHSA-42AA", "DEMO-OSV-1042"],
    packageName: "cipherleaf",
    installedVersion: "2.4.1",
    affectedRange: ">=2.1.0, <2.4.3",
    fixedVersion: "2.4.3",
    authoritativeConflict: true,
    advisoryGuidance: [
      {
        source: "Synthetic maintainer advisory",
        authority: "Maintainer · Tier 1",
        affectedRange: ">=2.1.0, <2.4.3",
        fixedVersion: "2.4.3",
        relationship: "contradicts",
      },
      {
        source: "Synthetic public vulnerability record",
        authority: "Public database · Tier 1",
        affectedRange: ">=2.1.0, <2.4.2",
        fixedVersion: "2.4.2",
        relationship: "contradicts",
      },
    ],
    dependencyType: "Transitive",
    dependencyPaths: [["harbor-api", "auth-gateway", "cipherleaf"]],
    kev: {
      state: "available",
      listed: true,
      observedAt: "2026-08-28T16:41:00Z",
      detail: "Synthetic known-exploitation observation for the precomputed demonstration.",
    },
    epss: {
      state: "available",
      score: 0.72,
      percentile: 0.96,
      observedAt: "2026-08-28T16:41:00Z",
      detail: "Synthetic EPSS observation for the precomputed demonstration.",
    },
    cvss: "8.1 · High",
  },
  validation: {
    materialClaimsSupported: false,
    validationIssues: ["claim-fix:material_claim_missing_support"],
  },
  recommendation: {
    label: "More Evidence Required",
    accepted: false,
    reason: "authoritative_evidence_conflict",
    summary:
      "Confirm the affected range and first patched release before choosing remediation.",
    reasons: [
      "The resolved version falls inside the affected range.",
      "Authoritative Sources disagree on the first patched release.",
      "No Source was selected as the winner; the conflict remains open.",
    ],
    limitations: [
      "The first patched release remains unresolved.",
      "Static imports do not establish runtime reachability or exploitability.",
    ],
  },
  policy: {
    assistanceClass: "C1 · Low-risk dual use",
    actionLevel: "A1 · Read",
    decision: "Allowed",
  },
  configuration: demoConfiguration,
  retrieval: {
    query: "cipherleaf 2.4.1 affected fixed upgrade",
    configurationVersion: "postgres-hybrid-rrf-v1",
    sourcePolicyVersion: "explicit-source-allowlist-v1",
    evidenceTypes: ["dependency", "affected", "remediation", "exploitation", "usage"],
    embeddingSpace: demoConfiguration.embeddingSpace,
  },
  stages: [
    { label: "Matched", mode: "deterministic", detail: "Version range and aliases normalized" },
    {
      label: "Retrieved",
      mode: "retrieval",
      detail: "PostgreSQL full-text + pgvector retrieval fused with deterministic RRF",
    },
    { label: "Interpreted", mode: "model", detail: "Claims synthesized locally" },
    {
      label: "Validated",
      mode: "policy",
      detail: "Claim support checked; an unsupported material Claim and authoritative conflict remain.",
    },
  ],
  claims: [
    {
      id: "claim-version",
      label: "C1",
      kind: "fact",
      material: true,
      supported: true,
      text: "The Asset Snapshot resolves cipherleaf 2.4.1, which is inside the published affected range.",
    },
    {
      id: "claim-fix",
      label: "C2",
      kind: "fact",
      material: true,
      supported: false,
      text: "The maintainer identifies version 2.4.3 as the first patched release.",
    },
    {
      id: "claim-priority",
      label: "C3",
      kind: "fact",
      material: true,
      supported: true,
      text: "The demonstration vulnerability is marked as known exploited and has a high synthetic EPSS percentile.",
    },
    {
      id: "claim-usage",
      label: "C4",
      kind: "inference",
      material: true,
      supported: true,
      text: "Static imports suggest the affected package is loaded by the authentication path.",
      limitation: "Import presence is context, not proof of runtime reachability or exploitability.",
    },
  ],
  evidence: [
    {
      id: "ev-lock",
      source: "uv.lock at 4f92c7d",
      authority: "Asset Snapshot",
      capturedAt: "2026-08-28 16:40 UTC",
      relationships: [{ claimId: "claim-version", relationship: "supports" }],
      passage: 'name = "cipherleaf" · version = "2.4.1" · via auth-gateway',
      fullTextRank: 1,
      fullTextScore: 0.941,
      vectorRank: 3,
      vectorScore: 0.812,
      fusedRank: 2,
      fusedScore: 0.0323,
      digest: "sha256:65bc…8a20",
    },
    {
      id: "ev-vendor",
      source: "Synthetic maintainer advisory",
      authority: "Maintainer · Tier 1",
      capturedAt: "2026-08-28 16:41 UTC",
      relationships: [
        { claimId: "claim-version", relationship: "contradicts" },
        { claimId: "claim-fix", relationship: "contradicts" },
      ],
      passage:
        "Releases from 2.1.0 through 2.4.2 are affected. Consumers should upgrade to cipherleaf 2.4.3 or later.",
      fullTextRank: 2,
      fullTextScore: 0.887,
      vectorRank: 1,
      vectorScore: 0.936,
      fusedRank: 1,
      fusedScore: 0.0325,
      digest: "sha256:21df…0c91",
    },
    {
      id: "ev-osv",
      source: "Synthetic public vulnerability record",
      authority: "Public database · Tier 1",
      capturedAt: "2026-08-28 16:41 UTC",
      relationships: [
        { claimId: "claim-version", relationship: "contradicts" },
        { claimId: "claim-fix", relationship: "contradicts" },
      ],
      passage:
        "The public record lists releases before 2.4.2 as affected and names 2.4.2 as fixed.",
      fullTextRank: 3,
      fullTextScore: 0.844,
      vectorRank: 2,
      vectorScore: 0.901,
      fusedRank: 3,
      fusedScore: 0.0320,
      digest: "sha256:44ea…a1c2",
    },
    {
      id: "ev-cisa",
      source: "Synthetic KEV record",
      authority: "Government · Tier 1",
      capturedAt: "2026-08-28 16:41 UTC",
      relationships: [{ claimId: "claim-priority", relationship: "supports" }],
      passage:
        "This synthetic record exists only to demonstrate how known-exploitation evidence changes investigation priority.",
      fullTextRank: 4,
      fullTextScore: 0.802,
      vectorRank: null,
      vectorScore: null,
      fusedRank: 4,
      fusedScore: 0.0156,
      digest: "sha256:8aa1…9f13",
    },
    {
      id: "ev-source",
      source: "services/api/auth/session.py",
      authority: "Repository context",
      capturedAt: "2026-08-28 16:40 UTC",
      relationships: [{ claimId: "claim-usage", relationship: "contextual" }],
      passage: "from cipherleaf.tokens import verify_session",
      fullTextRank: null,
      fullTextScore: null,
      vectorRank: 4,
      vectorScore: 0.774,
      fusedRank: 5,
      fusedScore: 0.0156,
      digest: "sha256:d10c…4b27",
    },
  ],
}
